# Generated by Django 5.0.1 on 2024-01-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Piss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("longitude", models.DecimalField(decimal_places=15, max_digits=30)),
                ("latitude", models.DecimalField(decimal_places=15, max_digits=30)),
                ("text", models.CharField(max_length=200)),
            ],
        ),
    ]
