# Generated by Django 5.0.1 on 2024-01-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pissmap", "0002_alter_piss_latitude_alter_piss_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piss",
            name="latitude",
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name="piss",
            name="longitude",
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name="piss",
            name="text",
            field=models.BinaryField(),
        ),
    ]
